# -*- coding: utf-8 -*-
"""Frequent_Pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BUm9GC0KV--Qbc-GEbA4mD3WOY6l2I4X

install pyfpgrowth
"""

!pip install pyfpgrowth

"""install apyori"""

!pip install apyori

"""import libraries 
    
"""

import pandas as pd
import pyfpgrowth
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from google.colab import drive
from apyori import apriori

"""import dirve"""

drive.mount('/content/drive')

"""preproccessing tarikhche kharid"""

orders_dataFrame = pd.read_csv("/content/drive/MyDrive/digikalaData/orders.csv" , sep = ",")
orders_dataFrame.drop_duplicates()
orders_dataFrame.dropna()
orders_dataFrame

"""transactions *Customer_id*"""

grouped_df_Customer = orders_dataFrame.groupby(by= ['ID_Customer'])
transactions_Customer = []
for group, pdf in grouped_df_Customer:
    transactions_Customer.append(pdf['ID_Item'].values.tolist())
transactions_Customer

"""Pattern Customer

"""

patterns_Customer = pyfpgrowth.find_frequent_patterns(transactions_Customer, 3)
patterns_Customer

"""Rules Customer"""

rules_Customer = pyfpgrowth.generate_association_rules(patterns_Customer, 0)
rules_Customer

"""transactions *ID_Order*"""

grouped_df = orders_dataFrame.groupby(by= ['ID_Order'])
transactions = []
for group, pdf in grouped_df:
    transactions.append(pdf['ID_Item'].values.tolist())
transactions

"""patterns ID Orders"""

patterns = pyfpgrowth.find_frequent_patterns(transactions, 1)
patterns

"""Rules ID Orders"""

rules = pyfpgrowth.generate_association_rules(patterns, 0.5)
rules

"""Apriori"""

association_rules = apriori(orders_dataFrame, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
association_results = list(association_rules)

association_results